/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.MySQL;

/**
 *
 * @author Oshadha
 */
public class EmployeeUpdate extends javax.swing.JFrame {
    
    private static HashMap<String, String> departmentMap = new HashMap<>();

    /**
     * Creates new form EmployeeUpdate
     */
    public EmployeeUpdate() {
        initComponents();
        loadEmployee();
        loadDepartment();
    }
    
     private void loadEmployee() {

        try {

            ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `employee`"
                    + "INNER JOIN `department` ON `employee`.`department_id`= `department`.`id`");
            
            } catch (Exception e) {
            e.printStackTrace();
        }
   } 
     private void  loadDepartment(){
         
         try {
             ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `department`");
             
             Vector<String> vector = new Vector<>();
             vector.add("Select");
             
             while (resultSet.next()) {
                  vector.add(resultSet.getString("dep_name"));
                  departmentMap.put(resultSet.getString("dep_name"), resultSet.getString("id"));
                 
             }
             
             DefaultComboBoxModel model = new DefaultComboBoxModel(vector);
             jComboBox1.setModel(model);
             
         } catch (Exception e) {
             e.printStackTrace();
         }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        jTextField8.setText("jTextField8");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 246, 209));

        jPanel3.setBackground(new java.awt.Color(255, 246, 209));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 158, 150, -1));

        jLabel3.setText("Last Name");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 136, 64, -1));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 102, 150, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 102, 105, -1));

        jLabel2.setText("First Name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 80, -1, -1));

        jLabel7.setText("Department");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 80, 80, -1));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 31, -1, -1));
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 339, 185, -1));

        jLabel1.setText("Enter NIC Number");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 6, 112, -1));

        jLabel6.setText("Address");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 317, 60, -1));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 32, 208, -1));
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 160, -1));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 283, -1, 42));

        jLabel5.setText("Email");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 249, 37, -1));

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 340, -1, -1));

        jLabel8.setText("Mobile");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 50, -1));
        jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 100, -1));

        jPanel1.setBackground(new java.awt.Color(255, 246, 237));
        jPanel1.setForeground(new java.awt.Color(255, 246, 237));

        jLabel10.setBackground(new java.awt.Color(255, 246, 209));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 51, 0));
        jLabel10.setText("Search Member");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        reset();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           try {
            String firstName = jTextField2.getText();
            String lastName  = jTextField3.getText();
           
            String email     = jTextField5.getText();
            String address   = jTextField6.getText();
            String department= String.valueOf(jComboBox1.getSelectedItem());
            String mobile    = jTextField7.getText();
            String nic       = jTextField1.getText();
            
               if (firstName.isEmpty()) {
                   JOptionPane.showMessageDialog(this, "Please Enter Your First Name", "Warning", JOptionPane.WARNING_MESSAGE);
                                
               } else if (lastName.isEmpty()) {
                   JOptionPane.showMessageDialog(this, "Please Enter Your Last Name","Warning",JOptionPane.WARNING_MESSAGE);
                   
                                
               } else if (email.isEmpty()) {
                   JOptionPane.showMessageDialog(this, "Please ENter Your Email","Warning",JOptionPane.WARNING_MESSAGE);
                   
                   
               } else if (!email.matches("^(?=.{1,64}@)[A-Za-z0-9\\+_-]+(\\.[A-Za-z0-9\\+_-]+)*@[^-][A-Za-z0-9\\+-]+"
                + "(\\.[A-Za-z0-9\\+-]+)*(\\.[A-Za-z]{2,})$")) {
                   JOptionPane.showMessageDialog(this, "Please Enter valid Email","Warning",JOptionPane.WARNING_MESSAGE);
                   
               } else if (address.isEmpty()) {
                   JOptionPane.showMessageDialog(this, "Please Enter Your Address");
                   
               } else if (department.equals("Select")) {
                   JOptionPane.showMessageDialog(this, "Please Select Your Department");
                   
               } else if (mobile.isEmpty()) {
                   JOptionPane.showMessageDialog(this, "Please Enter Your mobile Number");
                   
               } else if (!mobile.matches("^07[01245678]{1}[0-9]{7}$")) {
                   JOptionPane.showMessageDialog(this, "Please Enter Valid Mobile");
                   
               
        
               } else {
                   ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `employee` WHERE `nic`='"+nic+"'");
                   
                   boolean canUpadte = false;
                   
                   if (resultSet.next()) {
                       if (!resultSet.getString("email").equals(email)) {
                           JOptionPane.showMessageDialog(this, "This Email is already in use","Warning",JOptionPane.WARNING_MESSAGE);
                           
                       }else {
                           canUpadte = true;
                       }
                       
                       
                   } else {
                       canUpadte = true;
                   }
                   
                   if(canUpadte) {
                       String updateQuery = "UPDATE employee SET "
                               + "f_name = '" +firstName+ "', "
                               + "l_name  = '"+lastName+"', "
                              
                               + "mobile  = '"+mobile+"', "
                               + "email   = '"+email+"', "
                               + "address = '"+address+"', "
                               + "department_id = '"+departmentMap.get(department)+"' "
                               + "WHERE nic = '"+nic+"'";
                               MySQL.executeIUD(updateQuery);
                               
                                       
                   }
                   JOptionPane.showMessageDialog(this, "Employee Updated","Warning",JOptionPane.INFORMATION_MESSAGE);
               }
        } catch (Exception e) {
            e.printStackTrace();
        }
  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nic = jTextField1.getText();
        
        try {
            
           ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `employee` WHERE `nic` = '"+nic+"' ");
           
            if (resultSet.next()) {
                
                String firstName = resultSet.getString("f_name");
                jTextField2.setText(firstName);
                
                String lastName = resultSet.getString("l_name");
                jTextField3.setText(lastName);
                
             
                
                String email = resultSet.getString("email");
                jTextField5.setText(email);
                
                String address = resultSet.getString("address");
                jTextField6.setText(address);
                
                String department = resultSet.getString("department_id");
                jComboBox1.setSelectedItem(department);
                
                String mobile = resultSet.getString("mobile");
                jTextField7.setText(mobile);
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

    private void reset() {
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
  
    jTextField5.setText("");
    jTextField6.setText("");
    jTextField7.setText("");
    jComboBox1.setSelectedItem("");
   
    }
}
