/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;


import java.sql.ResultSet;
import java.text.MessageFormat;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.MySQL;

/**
 *
 * @author Oshadha
 */
public class outletRegistration extends javax.swing.JDialog {
    
     private static HashMap<String, String> managerMap = new HashMap<>();

    /**
     * Creates new form outletRegistration
     */
    public outletRegistration(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadOutlets();
        loadManager();
    }
    
    private void loadOutlets(){
        
        try {
            ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `outlet`"
                    + "INNER JOIN `outlet_manager` ON `outlet`.`outlet_manager_id`=`outlet_manager`.`id`");
            
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            
            while (resultSet.next()) {
               Vector<String> vector = new Vector<>();
               vector.add(resultSet.getString("id"));
               vector.add(resultSet.getString("name"));
               vector.add(resultSet.getString("mobile"));
               vector.add(resultSet.getString("address"));
               vector.add(resultSet.getString("outlet_manager.username"));
               model.addRow(vector);
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void loadManager(){
        
        try {
            ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `outlet_manager`");
            
            Vector<String> vector = new Vector<>();
            vector.add("Select");
            
            while (resultSet.next()) {
            vector.add(resultSet.getString("username"));
            managerMap.put(resultSet.getString("username"),resultSet.getString("id"));
            
                
            }
            
            DefaultComboBoxModel model = new DefaultComboBoxModel(vector);
            jComboBox1.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(252, 179, 143));
        jPanel1.setForeground(new java.awt.Color(255, 246, 237));

        jLabel10.setBackground(new java.awt.Color(255, 246, 209));
        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 51, 0));
        jLabel10.setText("Outlet Registration");

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 234, 218));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 290, 30));

        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 16)); // NOI18N
        jLabel3.setText("Mobile");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 290, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 290, 30));

        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 16)); // NOI18N
        jLabel2.setText("Outlet Name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 260, -1));

        jButton2.setBackground(new java.awt.Color(255, 246, 209));
        jButton2.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 140, -1));

        jButton3.setBackground(new java.awt.Color(255, 246, 209));
        jButton3.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 290, 40));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(255, 246, 209));
        jTable1.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Outlet Name", "Mobile", "Address", "Outlet Manager"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 820, 400));

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 16)); // NOI18N
        jLabel1.setText("Address");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 290, -1));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 290, 30));

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 16)); // NOI18N
        jLabel4.setText("Manager");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 290, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 290, 30));

        jButton1.setBackground(new java.awt.Color(255, 246, 209));
        jButton1.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, 180, 50));

        jButton4.setBackground(new java.awt.Color(255, 246, 209));
        jButton4.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jButton4.setText("Print");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 490, 160, 50));

        jButton5.setBackground(new java.awt.Color(255, 246, 209));
        jButton5.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jButton5.setText("Register");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1216, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try {
            
            String outlet = jTextField2.getText();
            String mobile = jTextField3.getText();
            String address = jTextField1.getText();
            String outletManager = String.valueOf(jComboBox1.getSelectedItem());
            
            if (outlet.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter Outlet Name","Warning",JOptionPane.WARNING_MESSAGE);
                
            } else if (mobile.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter Your Mobile","Warning",JOptionPane.WARNING_MESSAGE);
                
            } else if (!mobile.matches("^07[01245678]{1}[0-9]{7}$")) {
                JOptionPane.showMessageDialog(this, "Please Enter valid mobile", "Warning", JOptionPane.WARNING_MESSAGE);
                
            }else if (address.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter address","Warning",JOptionPane.WARNING_MESSAGE);
                
            }else if (outletManager.equals("Select")) {
                JOptionPane.showMessageDialog(this, "Please Select Manager","Warning",JOptionPane.WARNING_MESSAGE);
                
            }else  {
                ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `outlet` WHERE `mobile` ='"+mobile+"'");
                
                boolean canUpdate = false;
                
                if (resultSet.next()) {
                    
                    if (!resultSet.getString("mobile").equals(mobile)) {
                        JOptionPane.showMessageDialog(this, "This mobile is already used", "Warning",JOptionPane.WARNING_MESSAGE);
                        
                    } else {
                        canUpdate = true;
                    }
                    
                } else {
                    canUpdate = true;
                    
                }
                
                if (canUpdate) {
                    String updateQuery = "UPDATE outlet SET "
                            + "name = '"+outlet+"',"
                            + "mobile = '"+mobile+"',"
                            + "address ='"+address+"',"
                            + "outlet_manager_id ='"+ managerMap.get(outletManager)+"'"
                            + "WHERE mobile ='"+mobile+"'";
                            MySQL.executeIUD(updateQuery);
                            
                
                    
                
                  
                   
                    
                    
                    
                }
                JOptionPane.showMessageDialog(this, "Outlet Updated","Warning",JOptionPane.WARNING_MESSAGE);
                loadOutlets();
                    reset();
                 
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        reset();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {

            int selectedRow = jTable1.getSelectedRow();
            if(selectedRow != -1) {

                jTextField2.setText(String.valueOf(jTable1.getValueAt(selectedRow, 1)));
                jTextField3.setText(String.valueOf(jTable1.getValueAt(selectedRow, 2)));
                jTextField1.setText(String.valueOf(jTable1.getValueAt(selectedRow, 3)));
                jComboBox1.setSelectedItem(String.valueOf(jTable1.getValueAt(selectedRow, 4)));
            }

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            
            String outlet = jTextField2.getText();
            String mobile = jTextField3.getText();
            String address = jTextField1.getText();
            String outletManager = String.valueOf(jComboBox1.getSelectedItem());
            
            if (outlet.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter Outlet Name","Warning",JOptionPane.WARNING_MESSAGE);
                
            } else if (mobile.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter Your Mobile","Warning",JOptionPane.WARNING_MESSAGE);
                
            } else if (!mobile.matches("^07[01245678]{1}[0-9]{7}$")) {
                JOptionPane.showMessageDialog(this, "Please Enter valid mobile", "Warning", JOptionPane.WARNING_MESSAGE);
                
            }else if (address.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter address","Warning",JOptionPane.WARNING_MESSAGE);
                
            }else if (outletManager.equals("Select")) {
                JOptionPane.showMessageDialog(this, "Please Select Manager","Warning",JOptionPane.WARNING_MESSAGE);
                
            }else  {
                ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `outlet` WHERE `mobile` ='"+mobile+"'");
                
                if (resultSet.next()) {
                    JOptionPane.showMessageDialog(this, "This Outlet Already Registered","Warning",JOptionPane.WARNING_MESSAGE);
                    
                } else {
                    MySQL.executeIUD("INSERT INTO `outlet` (`name`,`mobile`,`address`,`outlet_manager_id`)"
                            + "VALUES('"+outlet+"','"+mobile+"','"+address+"',"
                            + "'"+managerMap.get(outletManager)+"')");
                    JOptionPane.showMessageDialog(this, "New Outlet registered","Warning",JOptionPane.WARNING_MESSAGE);
                    
                    loadOutlets();
                }
           
                 
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        MessageFormat header = new MessageFormat("I am Header of the Print Page");
        MessageFormat footer = new MessageFormat("Page{0, number, integer}");
        
        try {
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(outletRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(outletRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(outletRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(outletRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                outletRegistration dialog = new outletRegistration(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
       jComboBox1.setSelectedItem("Select");
    }
}
