/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.Frame;
import java.io.File;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.WInvoiceItem;
import model.MySQL;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author barth
 */
public class WInvoice extends javax.swing.JPanel {
    private WHome home;
    HashMap<String, WInvoiceItem> invoiceItemMap = new HashMap<>();
    HashMap<String, String> distributorMap = new HashMap<>();

    /**
     * Creates new form Overview
     */
    public WInvoice(WHome home) {
        initComponents();
        this.home = home;
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        invoiceItemTable.setDefaultRenderer(Object.class, renderer);
        //wSupervisorIDLabel.setText(SignIn.getWSupervisorID());
        generateInvoiceID();
        loadDistributors();
    }
    
    private void generateInvoiceID() {
        long id = System.currentTimeMillis();
        invoiceIDField.setText(String.valueOf(id));
    }
    
    public JTextField getinvoiceIDField() {
        return invoiceIDField;
    }
    
    public JTextField getorderIDField() {
        return orderIDField;
    }
    
    public JLabel getoutletNameLabel() {
        return outletNameLabel;
    }

    public JTable getinvoiceItemTable() {
        return invoiceItemTable;
    }
    
    public JLabel gettotalLabel() {
        return totalLabel;
    }
    
    private double total = 0;
    private double discount = 0;
    private double grandTotal = 0;
    
    private void calculate() {
        if (discountFormattedField.getText().isEmpty()) {
            discount = 0;
        }else {
            discount = Double.parseDouble(discountFormattedField.getText());
        }
        
        total = Double.parseDouble(totalLabel.getText());
        grandTotal = total - discount;
        
        if (grandTotal < 0) {
            printButton.setEnabled(false);
        }else {
            printButton.setEnabled(true);
        }
        
        grandTotalLabel.setText(String.valueOf(grandTotal));
    }
    
    private void loadDistributors() {
        try {
            ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `distributor`");
            Vector<String> vector = new Vector<>();
            vector.add("Select");
            
            while (resultSet.next()) {
                vector.add(resultSet.getString("name"));
                distributorMap.put(resultSet.getString("name"), resultSet.getString("id"));
            }
            
            DefaultComboBoxModel model = new DefaultComboBoxModel(vector);
            distributorComboBox.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void reset() {
        generateInvoiceID();
        orderIDField.setText("");
        outletNameLabel.setText("OUTLET NAME");
        DefaultTableModel model = (DefaultTableModel) invoiceItemTable.getModel();
        model.setRowCount(0);
        totalLabel.setText("0.00");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoiceItemTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        wSupervisorIDLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        invoiceIDField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        outletNameLabel = new javax.swing.JLabel();
        selectOrderButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        orderIDField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        distributorComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        discountFormattedField = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        printButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        grandTotalLabel = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/close-icon.png"))); // NOI18N
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });

        invoiceItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product", "Qty", "Price", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        invoiceItemTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(invoiceItemTable);

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(66, 45, 22));
        jLabel2.setText("Invoice");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setText("W. Supervisor :");

        wSupervisorIDLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        wSupervisorIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wSupervisorIDLabel.setText("W. SUPERVISOR ID");
        wSupervisorIDLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 171, 77)));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setText("Invoice ID :");

        invoiceIDField.setEditable(false);
        invoiceIDField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setText("Order ID :");

        outletNameLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        outletNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outletNameLabel.setText("OUTLET NAME");
        outletNameLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 171, 77)));

        selectOrderButton.setBackground(new java.awt.Color(245, 219, 200));
        selectOrderButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        selectOrderButton.setForeground(new java.awt.Color(0, 0, 0));
        selectOrderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/select-icon.png"))); // NOI18N
        selectOrderButton.setText("Select Order");
        selectOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectOrderButtonActionPerformed(evt);
            }
        });

        resetButton.setBackground(new java.awt.Color(245, 219, 200));
        resetButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        resetButton.setForeground(new java.awt.Color(0, 0, 0));
        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/reset-icon.png"))); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel17.setText("Outlet :");

        orderIDField.setEditable(false);
        orderIDField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setText("Distributor :");

        distributorComboBox.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        distributorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orderIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wSupervisorIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(invoiceIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(distributorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(outletNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(selectOrderButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeLabel)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(wSupervisorIDLabel)
                    .addComponent(jLabel6)
                    .addComponent(invoiceIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(distributorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(orderIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(outletNameLabel)
                    .addComponent(resetButton)
                    .addComponent(selectOrderButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel1.setText("Total :");

        totalLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalLabel.setText("0.00");
        totalLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 171, 77)));

        discountFormattedField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        discountFormattedField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        discountFormattedField.setText("0");
        discountFormattedField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        discountFormattedField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                discountFormattedFieldKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel16.setText("Discount :");

        printButton.setBackground(new java.awt.Color(245, 219, 200));
        printButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        printButton.setForeground(new java.awt.Color(0, 0, 0));
        printButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/print-icon.png"))); // NOI18N
        printButton.setText("Print Invoice");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setText("Grand Total :");

        grandTotalLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        grandTotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        grandTotalLabel.setText("0.00");
        grandTotalLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 171, 77)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(printButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel16)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(discountFormattedField, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(grandTotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(totalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discountFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(grandTotalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        this.home.removeInvoice();
    }//GEN-LAST:event_closeLabelMouseClicked

    private void selectOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectOrderButtonActionPerformed
        WSelectOrder selectOrder = new WSelectOrder((Frame) SwingUtilities.getWindowAncestor(this), true, this);
        selectOrder.setVisible(true);
    }//GEN-LAST:event_selectOrderButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        reset();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void discountFormattedFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discountFormattedFieldKeyReleased
        double totalLabelText = Double.parseDouble(totalLabel.getText());
        double discountFieldText = Double.parseDouble(discountFormattedField.getText());
        
        if (totalLabelText < discountFieldText) {
            printButton.setEnabled(false);
            grandTotalLabel.setText("INVALID");
            grandTotalLabel.setForeground(Color.red);
        }else if (!discountFormattedField.getText().matches("^(0|[1-9]\\d*)?(\\.\\d+)?(?<=\\d)$")) {
            printButton.setEnabled(false);
            grandTotalLabel.setText("INVALID");
            grandTotalLabel.setForeground(Color.red);
        }else {
            printButton.setEnabled(true);
            grandTotalLabel.setForeground(Color.black);
            calculate();
        }
    }//GEN-LAST:event_discountFormattedFieldKeyReleased

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        try {
            ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `w_invoice` WHERE `id` = '"+invoiceIDField.getText()+"'");
            
            if (resultSet.next()) {
                JOptionPane.showMessageDialog(this, "This invoice already exists", "Warning", JOptionPane.WARNING_MESSAGE);
            }else {
                String wSupervisorID = wSupervisorIDLabel.getText();
                String invoiceID = invoiceIDField.getText();
                String orderID = orderIDField.getText();
                String distributorID = distributorMap.get(String.valueOf(distributorComboBox.getSelectedItem()));
                String dateTime = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
                String total = totalLabel.getText();
                String discount = String.valueOf(discountFormattedField.getText());
                int rowCount = invoiceItemTable.getRowCount();
                
                if (rowCount == 0) {
                    JOptionPane.showMessageDialog(this, "Please add item(s) to invoice", "Warning", JOptionPane.WARNING_MESSAGE);
                }else {
                    MySQL.executeIUD("INSERT INTO `w_invoice` VALUES('"+invoiceID+"', '"+dateTime+"', '"+total+"', "
                            + "'"+discount+"', '"+wSupervisorID+"', '"+orderID+"', '"+distributorID+"')");
                    
                    ResultSet resultSet1 = MySQL.executeSearch("SELECT * FROM `order` INNER JOIN `order_items` "
                            + "ON `order`.`id` = `order_items`.`order_id` INNER JOIN `product` "
                            + "ON `order_items`.`product_id` = `product`.`id` "
                            + "INNER JOIN `category` ON `product`.`category_id` = `category`.`id` "
                            + "WHERE `order`.`id` = '"+orderIDField.getText()+"' "
                            + "AND `category`.`name` = 'Drinks'");
                    
                    while (resultSet1.next()) {
                        MySQL.executeIUD("UPDATE `w_stock` SET `qty` = `qty`-'"+resultSet1.getString("order_items.qty")+"' "
                                + "WHERE `w_stock`.`product_id` = '"+resultSet1.getString("product.id")+"'");
                    }
                            
                    InputStream path = this.getClass().getResourceAsStream("/reports/w_invoice.jasper");
                    HashMap<String, Object> parameters = new HashMap<>();
                    parameters.put("Parameter1", wSupervisorIDLabel.getText());
                    parameters.put("Parameter2", invoiceIDField.getText());
                    parameters.put("Parameter3", orderIDField.getText());
                    parameters.put("Parameter4", outletNameLabel.getText());
                    parameters.put("Parameter5", distributorComboBox.getSelectedItem());
                    parameters.put("Parameter6", dateTime);
                    parameters.put("Parameter7", totalLabel.getText());
                    parameters.put("Parameter8", discountFormattedField.getText());
                    parameters.put("Parameter9", grandTotalLabel.getText());

                    String appDir = new File("").getAbsolutePath(); // Get the application's directory
                    String reportsFolder = appDir + File.separator + "ExportedReports"; // Main folder path
                    // Create the main "ExportedReports" folder if it doesn't exist
                    File mainDirectory = new File(reportsFolder);
                    if (!mainDirectory.exists()) {
                        mainDirectory.mkdirs();
                    }
                    // Create subfolder for "Invoice Reports" if it doesn't exist
                    String invoiceReportsFolder = reportsFolder + File.separator + "Invoice Reports";
                    File invoiceDirectory = new File(invoiceReportsFolder);
                    if (!invoiceDirectory.exists()) {
                        invoiceDirectory.mkdirs();
                    }
                    // Path to export the PDF file (inside "Invoice Reports" subfolder)
                    String outputPath = invoiceReportsFolder + File.separator + "Invoice_report_" + invoiceID + ".pdf";

                    JRTableModelDataSource dataSource = new JRTableModelDataSource(invoiceItemTable.getModel());
                    JasperPrint report = JasperFillManager.fillReport(path, parameters, dataSource);
                    JasperViewer.viewReport(report, false);
                    JasperPrintManager.printReport(report, false);
                    JasperExportManager.exportReportToPdfFile(report, outputPath);
                    reset();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_printButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeLabel;
    private javax.swing.JFormattedTextField discountFormattedField;
    private javax.swing.JComboBox<String> distributorComboBox;
    private javax.swing.JLabel grandTotalLabel;
    private javax.swing.JTextField invoiceIDField;
    private javax.swing.JTable invoiceItemTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField orderIDField;
    private javax.swing.JLabel outletNameLabel;
    private javax.swing.JButton printButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton selectOrderButton;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel wSupervisorIDLabel;
    // End of variables declaration//GEN-END:variables
}
