/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import model.MySQL;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author barth
 */
public class WSelectReturnSlip extends javax.swing.JDialog {
    private WReturns returns;
    private double total = 0;

    /**
     * Creates new form CompanyRegistration
     */
    public WSelectReturnSlip(java.awt.Frame parent, boolean modal, WReturns returns) {
        super(parent, modal);
        this.returns = returns;
        initComponents();
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        pendingReturnSlipTable.setDefaultRenderer(Object.class, renderer);
        loadPendingReturnSlips();
    }
    
    private void loadPendingReturnSlips() {
        try {
            ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `return_slip` INNER JOIN `return_invoice` "
                    + "ON `return_slip`.`return_invoice_id` = `return_invoice`.`id` INNER JOIN `outlet` "
                    + "ON `return_invoice`.`outlet_id` = `outlet`.`id` INNER JOIN `delivery` "
                    + "ON `return_invoice`.`delivery_id` = `delivery`.`id` INNER JOIN `return_slip_status` "
                    + "ON `return_slip`.`return_slip_status_id` = `return_slip_status`.`id` "
                    + "WHERE `return_slip_status`.`name` = 'Pending'");
            DefaultTableModel model = (DefaultTableModel) pendingReturnSlipTable.getModel();
            model.setRowCount(0);
            
            while (resultSet.next()) {
                Vector<String> vector = new Vector<>();
                vector.add(resultSet.getString("return_slip.id"));
                vector.add(resultSet.getString("return_invoice.id"));
                vector.add(resultSet.getString("outlet.name"));
                vector.add(resultSet.getString("delivery.delivery_date"));
                model.addRow(vector);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pendingReturnSlipTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Outlet");

        jPanel1.setBackground(new java.awt.Color(245, 219, 200));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 45, 22));
        jLabel1.setText("Select Return Slip");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pendingReturnSlipTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Slip ID", "Ret. Inv. ID", "Outlet Name", "Delivery Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pendingReturnSlipTable.getTableHeader().setReorderingAllowed(false);
        pendingReturnSlipTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendingReturnSlipTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pendingReturnSlipTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pendingReturnSlipTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendingReturnSlipTableMouseClicked
        //logger.log(Level.INFO, "MouseEvent");
        int row = pendingReturnSlipTable.getSelectedRow();
        
        if (evt.getClickCount() == 2) {
            try {
                if (returns != null) {
                    returns.getslipIDField().setText(String.valueOf(pendingReturnSlipTable.getValueAt(row, 0)));
                    returns.getreturnInvoiceIDField().setText(String.valueOf(pendingReturnSlipTable.getValueAt(row, 1)));
                    returns.getoutletNameLabel().setText(String.valueOf(pendingReturnSlipTable.getValueAt(row, 2)));
                    returns.getdeliveryDateLabel().setText(String.valueOf(pendingReturnSlipTable.getValueAt(row, 3)));
                    
                    ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `return_slip` INNER JOIN `return_invoice` "
                            + "ON `return_slip`.`return_invoice_id` = `return_invoice`.`id` INNER JOIN `outlet` "
                            + "ON `return_invoice`.`outlet_id` = `outlet`.`id` INNER JOIN `delivery` "
                            + "ON `return_invoice`.`delivery_id` = `delivery`.`id` INNER JOIN `distributor` "
                            + "ON `return_invoice`.`distributor_id` = `distributor`.`id` "
                            + "WHERE `return_slip`.`id` = '"+String.valueOf(pendingReturnSlipTable.getValueAt(row, 0))+"'");
                    
                    returns.getoutletAddressLabel().setText(resultSet.getString("outlet.address"));
                    returns.gettimeLabel().setText(resultSet.getString("return_invoice.time"));
                    returns.getvehicleNumberLabel().setText(resultSet.getString("distributor.vehicle_no"));
                    returns.getoutletManagerIDField().setText(resultSet.getString("return_slip.outlet_manager_id"));
                    
                    this.dispose();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_pendingReturnSlipTableMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pendingReturnSlipTable;
    // End of variables declaration//GEN-END:variables
}
