/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

//import static gui.SignIn.logger;
import model.MySQL;
import java.sql.ResultSet;
import java.util.Vector;
//import java.util.logging.Level;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author barth
 */
public class WSelectReturnStock extends javax.swing.JDialog {
    private WReturns wReturns;
    
    /**
     * Creates new form CompanyRegistration
     */
    public WSelectReturnStock(java.awt.Frame parent, boolean modal, WReturns wReturns) {
        super(parent, modal);
        this.wReturns = wReturns;
        initComponents();
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        returnStockTable.setDefaultRenderer(Object.class, renderer);
        loadStock();
    }
    
    private void loadStock() {
        try {
            String query = "SELECT * FROM `returning_stock` INNER JOIN `w_stock` "
                    + "ON `returning_stock`.`w_stock_id` = `w_stock`.`id` INNER JOIN `w_grn_item` "
                    + "ON `w_stock`.`id` = `w_grn_item`.`w_stock_id` INNER JOIN `w_grn` "
                    + "ON `w_grn_item`.`w_grn_id` = `w_grn`.`id` INNER JOIN `w_product` "
                    + "ON `w_stock`.`w_product_id` = `w_product`.`id` INNER JOIN `supplier` "
                    + "ON `w_grn`.`supplier_id` = `supplier`.`id` INNER JOIN `returning_stock_status` "
                    + "ON `returning_stock`.`returning_stock_status_id` = `returning_stock_status`.`id` "
                    + "WHERE `supplier`.`id` = '"+wReturns.suppliersMap.get(wReturns.getsupplierEmailLabel().getText())+"' "
                    + "AND `returning_stock_status`.`name` = 'Pending'";
            ResultSet resultSet = MySQL.executeSearch(query);
            DefaultTableModel model = (DefaultTableModel)returnStockTable.getModel();
            model.setRowCount(0);
            
            while (resultSet.next()) {
                Vector<String> vector = new Vector<>();
                vector.add(resultSet.getString("returning_stock.id"));
                vector.add(resultSet.getString("w_product.name"));
                vector.add(resultSet.getString("w_product.weight"));
                vector.add(resultSet.getString("returning_stock.qty"));
                vector.add(resultSet.getString("w_grn_item.price"));
                model.addRow(vector);
            }
        } catch (Exception e) {
            e.printStackTrace();
            //logger.log(Level.WARNING, "Exception", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        returnStockTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Product");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 45, 22));
        jLabel1.setText("Select Return Stock");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        returnStockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "R. Stock ID", "Product Name", "Product Weight", "Quantity", "Buying Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        returnStockTable.getTableHeader().setReorderingAllowed(false);
        returnStockTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnStockTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(returnStockTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void returnStockTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnStockTableMouseClicked
        //logger.log(Level.INFO, "MouseEvent");
        int row = returnStockTable.getSelectedRow();
        
        if (evt.getClickCount() == 2) {
            if (wReturns != null) {
                wReturns.getreturningStockIDLabel().setText(String.valueOf(returnStockTable.getValueAt(row, 0)));
                wReturns.getproductNameLabel().setText(String.valueOf(returnStockTable.getValueAt(row, 1)));
                wReturns.getproductWeightLabel().setText(String.valueOf(returnStockTable.getValueAt(row, 2)));
                wReturns.getquantityLabel().setText(String.valueOf(returnStockTable.getValueAt(row, 3)));
                wReturns.getbuyingPriceLabel().setText(String.valueOf(returnStockTable.getValueAt(row, 4)));
                this.dispose();
            }
        }
    }//GEN-LAST:event_returnStockTableMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //logger.log(Level.INFO, "WindowEvent");
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //logger.log(Level.INFO, "WindowEvent");
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable returnStockTable;
    // End of variables declaration//GEN-END:variables
}
